name: wp_course_alt

weights:
    r_course:
        scale: 3.141592 # pi
        clip_max: 1.0
        weight: 0.5 # 0.45
    r_alt:
        scale: 30
        clip_max: 1.0
        weight: 0.5 # 0.45
