name: wp_prog
weights:
    r_prog:
        scale: 6.25
        clip_min: -1.5
    act_var:
        enabled: False
        max_r: 0.0
        tanh_scale: 0.0
    r_airspeed:
        enabled: False
        max_r: 0.3
        tanh_scale: 0.05