### task specific child class config: ACBohnTask ###
obs_is_matrix: false
obs_hist_size: 1

action_avg: false
act_hist_size: 5

### For Dubins Path Tracking Task ###
rho_min: 40.0 # minimum turning radius [m]
pitch_max: [-15.0, 20.0] # pitch limits [deg]
dub_sampling_dist: 15.0 # distance between Dubins path points [m]
dub_switch_dist: 10.0 # distance for switching to next Dubins path point [m]
