### TDMPC2 config ###
# environment
task: ACBohnNoVaIErr
obs: state

# training
steps: 750_000
# reference attitude angle limits (+/- degrees)
roll_limit: 60 # 45 up to moderate, 60 up to hard
pitch_limit: 30 # 25 up to moderate, 30 up to hard

# eval during training
periodic_eval: true
eval_freq: 37_500 # This will make 20 evaluations points
eval_episodes: ??? # this value is overwritten by the size of the reference sequence in the code
final_traj_plot: true # simulate a final trajectory at the end of training (for visualization + log in wandb)

# standalone eval
ref_file: simple_easy
res_file: test
evaluated_traj_file: tdmpc2_evaluation_episodes
metrics_file: tdmpc2_metrics_results
im_traj: false
dec_obs: false

# logging
wandb_project: uav_rl
wandb_entity: thesedavid
wandb_silent: false
disable_wandb: false

# arch
use_enc: true
use_decoder: false
gaussian_dyn: false

# misc
save_agent: true
seed: ???
render_mode: 'none'

# CAPS
use_caps: false
ts_coef: 0.0

num_envs: 1 # number of parallel environments (tdmpc2 only support 1 atm)
