# parent class JSBSimEnv config
fdm_freq: 100.0 # 120 Hz being the default JSBSim freq
agent_freq: 100.0
episode_length_s: 20.0
viz_time_factor: 50.0
debug: True
render_mode: "none"

# settings for env with light constant wind and all turbulence levels
# JSBSim simulation env options - train
train_sim_options:
    seed: ???
    atmosphere:
        severity: null
        variable: True
        wind:
            enable: True
            # wind_dir: [0.0, 1.0, 0.0] # North, East, Down
            wind_severity: 5.0
            rand_windspeed: False
        turb:
            enable: False
        gust:
            enable: False
    rand_fdm:
        enable: False

# JSBSim simulation env options - eval
eval_sim_options:
    seed: ???
    atmosphere:
        severity: null
        variable: False
        wind:
            enable: True
            wind_dir: ??? # North, East, Down, if unspecified, wind_dir is random
            rand_windspeed: False # if True, wind_severity is ignored
            wind_severity: ??? # off, light, moderate, severe, float (for custom wind speed)
        turb:
            enable: False
        gust:
            enable: False
    rand_fdm:
        enable: False